import { useState } from 'react'
import type { EmployeeInput } from '../../hooks/useAutoPayData'
import type { Employee } from '../../lib/autopay-data'
import type { SetView } from '../../types'

export function EmployeeFormPage({ employee, saveEmployee, setView }: { employee?: Employee; saveEmployee: (input: EmployeeInput, existingId?: string) => Promise<void>; setView: SetView }) {
  const [form, setForm] = useState<EmployeeInput>({ name: employee?.name ?? '', role: employee?.role ?? '', department: employee?.department ?? 'Operations', paymentMethod: employee?.paymentMethod ?? 'Mobile Money', salaryStructure: employee?.salaryStructure ?? 'Monthly Fixed', status: employee?.status ?? 'Onboarding', phone: employee?.phone ?? '', salary: employee?.salary ?? 'NGN 0', avatarUrl: employee?.avatarUrl ?? '' })
  const updateForm = (key: keyof EmployeeInput, value: string) => setForm((current) => ({ ...current, [key]: value }))
  return <section className="panel form-panel"><header><h3>{employee ? 'Edit Employee' : 'Add Employee'}</h3><span>Production form</span></header><div className="form-grid"><label>Full name<input value={form.name} onChange={(event) => updateForm('name', event.target.value)} /></label><label>Role<input value={form.role} onChange={(event) => updateForm('role', event.target.value)} /></label><label>Department<input value={form.department} onChange={(event) => updateForm('department', event.target.value)} /></label><label>Phone / Wallet<input value={form.phone} onChange={(event) => updateForm('phone', event.target.value)} /></label><label>Salary<input value={form.salary} onChange={(event) => updateForm('salary', event.target.value)} /></label><label>Avatar URL<input value={form.avatarUrl} onChange={(event) => updateForm('avatarUrl', event.target.value)} /></label><label>Payment method<select value={form.paymentMethod} onChange={(event) => updateForm('paymentMethod', event.target.value)}><option>Mobile Money</option><option>Bank Transfer</option></select></label><label>Status<select value={form.status} onChange={(event) => updateForm('status', event.target.value)}><option>Active</option><option>On Leave</option><option>Onboarding</option></select></label></div><button className="primary" type="button" onClick={() => saveEmployee(form, employee?.id).then(() => setView('employees'))}>Save Employee</button></section>
}
